// =============================================================
//  IRELAND TRIP DATA  –  October 2026 Edition
// =============================================================

const TRIP = {
  title: '🍀 Ireland Trip',
  subtitle: 'October 2026 · 4 Regions · 12 Nights · Autumn Weather & Nature Trails',
  dates: { start: 'Oct 2', end: 'Oct 14' },
  housing: [
    { name: 'Walnut Retreat', region: 'ni', base: 'Newry', dates: 'Oct 2–5 (3 nights)', checkin: '11:30 AM Oct 2', checkout: '11:00 AM Oct 5' },
    { name: 'Spiddal Villa', region: 'galway', base: 'Spiddal', dates: 'Oct 5–8 (3 nights)', checkin: '4:00 PM Oct 5', checkout: '11:00 AM Oct 8' },
    { name: 'Milltown House', region: 'kerry', base: 'Killarney', dates: 'Oct 8–11 (3 nights)', checkin: '12:00 PM Oct 8', checkout: '8:00 AM Oct 11' },
    { name: 'Navan Home', region: 'dublin', base: 'Navan', dates: 'Oct 11–14 (3 nights)', checkin: '3:00 PM Oct 11', checkout: '11:00 AM Oct 14' }
  ]
};

// ── Regions ──────────────────────────────────────────────────
const regions = [
  {
    id: 'ni',
    name: 'Northern Ireland',
    sub: 'Newry Base · Oct 2–5',
    color: '#10b981',
    ratings: { nature: 8, city: 7, history: 9, culture: 8, food: 8, activities: 8, sport: 7, scenic: 9 },
    notes: 'Giants Causeway, Belfast city, Titanic, Mourne Mountains, crisp coastal weather',
  },
  {
    id: 'galway',
    name: 'Galway / Connemara',
    sub: 'Spiddal Base · Oct 5–8',
    color: '#3b82f6',
    ratings: { nature: 10, city: 7, history: 7, culture: 9, food: 8, activities: 7, sport: 6, scenic: 10 },
    notes: 'Cliffs of Moher, wild Connemara hikes, Kylemore Abbey, vibrant Latin Quarter, The Burren',
  },
  {
    id: 'kerry',
    name: 'Kerry / Killarney',
    sub: 'Milltown Base · Oct 8–11',
    color: '#8b5cf6',
    ratings: { nature: 10, city: 5, history: 7, culture: 8, food: 9, activities: 9, sport: 8, scenic: 10 },
    notes: 'Killarney National Park, Dingle Peninsula, Slea Head, Gap of Dunloe, rich food scene',
  },
  {
    id: 'dublin',
    name: 'Dublin / East',
    sub: 'Navan Base · Oct 11–14',
    color: '#f59e0b',
    ratings: { nature: 4, city: 10, history: 9, culture: 9, food: 9, activities: 8, sport: 7, scenic: 3 },
    notes: "Temple Bar, Guinness, Newgrange, Kilkenny, lively pub scene, Mom's birthday!",
  },
];

// ── Attractions per region ────────────────────────────────────
const attractions = {
  ni: [
    { name: 'Giants Causeway',              nature: 10, history: 8,  culture: 7,  activity: 8,  time: '2–3h',   dist: '2h 15m from Newry' },
    { name: 'Titanic Museum',               nature: 1,  history: 10, culture: 9,  activity: 7,  time: '2–3h',   dist: '1h (Belfast)' },
    { name: 'Peace Wall + Black Cab Tour',  nature: 1,  history: 10, culture: 10, activity: 8,  time: '1.5–2h', dist: '1h (Belfast)' },
    { name: "St. Anne's Cathedral",         nature: 1,  history: 8,  culture: 8,  activity: 4,  time: '30–45m', dist: '1h (Belfast)' },
    { name: "St. George's Market",          nature: 1,  history: 3,  culture: 9,  activity: 7,  time: '1–2h',   dist: '1h (Belfast)' },
    { name: 'Carrick-a-Rede Rope Bridge',   nature: 9,  history: 5,  culture: 4,  activity: 9,  time: '1–1.5h', dist: '2h 20m from Newry' },
    { name: 'Old Bushmills Distillery',     nature: 2,  history: 7,  culture: 8,  activity: 7,  time: '1.5h',   dist: '2h 10m from Newry' },
    { name: 'Kilbroney Park Forest',        nature: 9,  history: 2,  culture: 2,  activity: 7,  time: '1.5–2h', dist: '15m from Newry' },
    { name: 'Slieve Gullion Forest',        nature: 9,  history: 4,  culture: 3,  activity: 8,  time: '2–3h',   dist: '20m from Newry' },
    { name: 'Mourne AONB',                  nature: 10, history: 3,  culture: 3,  activity: 9,  time: '3–5h',   dist: '30m from Newry' },
    { name: 'Coastal Causeway Route',       nature: 9,  history: 5,  culture: 6,  activity: 6,  time: '4–6h',   dist: 'Belfast → Derry' },
    { name: "Bagenal's Castle",             nature: 1,  history: 8,  culture: 6,  activity: 4,  time: '1h',     dist: '5m (Newry)' },
    { name: 'Derrymore House',              nature: 6,  history: 7,  culture: 5,  activity: 3,  time: '1h',     dist: '10m from Newry' },
    { name: 'Ballymacdermott Court Tomb',   nature: 5,  history: 8,  culture: 4,  activity: 3,  time: '30m',    dist: '10m from Newry' },
  ],
  galway: [
    { name: 'Cliffs of Moher',        nature: 10, history: 3, culture: 5,  activity: 7, time: '2–3h',  dist: '1h 10m south' },
    { name: 'Connemara National Park',nature: 10, history: 2, culture: 3,  activity: 8, time: '3–4h',  dist: '50m' },
    { name: 'Kylemore Abbey',         nature: 8,  history: 8, culture: 7,  activity: 5, time: '2–3h',  dist: '1h 10m' },
    { name: 'Dunguaire Castle',       nature: 5,  history: 8, culture: 7,  activity: 4, time: '1h',    dist: '35m' },
    { name: 'Galway City (explore)',  nature: 2,  history: 5, culture: 10, activity: 8, time: '3–5h',  dist: '20m' },
    { name: 'Burren National Park',   nature: 9,  history: 6, culture: 4,  activity: 7, time: '2–3h',  dist: '50m' },
    { name: 'Cong (Ashford Castle)',  nature: 7,  history: 8, culture: 6,  activity: 5, time: '2–3h',  dist: '1h 15m' },
  ],
  kerry: [
    { name: 'Killarney National Park',nature: 10, history: 5,  culture: 4, activity: 9,  time: '3–5h',  dist: '15m' },
    { name: 'Ross Castle',            nature: 6,  history: 9,  culture: 7, activity: 5,  time: '1–1.5h',dist: '10m' },
    { name: 'Torc Waterfall',         nature: 9,  history: 1,  culture: 1, activity: 6,  time: '30–45m',dist: '15m' },
    { name: 'Muckross Abbey',         nature: 6,  history: 9,  culture: 7, activity: 4,  time: '45m–1h',dist: '10m' },
    { name: 'Gap of Dunloe',          nature: 10, history: 3,  culture: 4, activity: 9,  time: '3–4h',  dist: '25m' },
    { name: 'Dingle Peninsula',       nature: 9,  history: 6,  culture: 9, activity: 7,  time: '4–6h',  dist: '1h 10m' },
    { name: 'Slea Head Drive',        nature: 10, history: 5,  culture: 6, activity: 6,  time: '2–3h',  dist: '1h 20m (via Dingle)' },
    { name: 'Cork (day trip)',         nature: 3,  history: 6,  culture: 8, activity: 7,  time: '4–6h',  dist: '1h 20m' },
    { name: 'Rock of Cashel',         nature: 3,  history: 10, culture: 8, activity: 5,  time: '1–1.5h',dist: '1h 50m (otw Dublin)' },
    { name: 'Strickeen Mountain',     nature: 10, history: 1,  culture: 1, activity: 10, time: '2–3h',  dist: '25m' },
  ],
  dublin: [
    { name: 'Newgrange Monument',      nature: 4, history: 10, culture: 8,  activity: 6, time: '2–3h',  dist: '20m from Navan' },
    { name: 'Kilkenny (pit stop)',     nature: 3, history: 9,  culture: 8,  activity: 7, time: '3–4h',  dist: '1h 45m from Navan' },
    { name: "Smithwick's Experience",  nature: 1, history: 7,  culture: 8,  activity: 7, time: '1.5h',  dist: 'In Kilkenny' },
    { name: 'Guinness Storehouse',     nature: 1, history: 8,  culture: 9,  activity: 8, time: '2–3h',  dist: '50m (Dublin)' },
    { name: 'Temple Bar Crawl',        nature: 1, history: 5,  culture: 10, activity: 9, time: '3–5h',  dist: '50m (Dublin)' },
    { name: "St. Patrick's Cathedral", nature: 2, history: 9,  culture: 8,  activity: 4, time: '45m–1h',dist: '50m (Dublin)' },
    { name: 'General Post Office',     nature: 1, history: 10, culture: 7,  activity: 4, time: '45m–1h',dist: '50m (Dublin)' },
    { name: 'Brazen Head (oldest pub)',nature: 1, history: 8,  culture: 9,  activity: 7, time: '1–2h',  dist: '50m (Dublin)' },
  ],
};

// ── October 2026 Weather Patterns & Forecast ─────────────────
const weatherData = {
  general: {
    title: 'Autumn in Ireland (October 2026)',
    tempRange: '8°C – 14°C (46°F – 58°F)',
    daylight: 'Sunrise ~7:45 AM · Sunset ~6:35 PM (10.5 hrs light)',
    rainfall: 'Typical Atlantic passing fronts (45–60% rain probability, light mist to brisk showers)',
    winds: 'Moderate to Fresh breeze (15–30 km/h, gusting to 45+ km/h on Atlantic cliffs)',
    advice: 'Layering is king: Waterproof breathable outer shell + warm fleece mid-layer + thermal base. Do not rely on umbrellas on coastal cliffs!'
  },
  regionalOverview: [
    {
      region: 'Northern Ireland (Newry & Causeway Coast)',
      highLow: '13°C / 7°C (55°F / 45°F)',
      conditions: 'Brisk coastal winds, passing showers, crisp morning sea air',
      outfitRecommendation: 'Windproof Gore-Tex shell, fleece jacket, waterproof hiking boots with grip, beanie for coastal cliffs.'
    },
    {
      region: 'Galway & Connemara (West Atlantic Coast)',
      highLow: '14°C / 8°C (57°F / 46°F)',
      conditions: 'Frequent Atlantic squalls, dramatic shifting light, gusty cliffs',
      outfitRecommendation: 'Heavy-duty waterproofs, rain pants for Diamond Hill/Cliffs of Moher, thermal layers, warm wool socks.'
    },
    {
      region: 'Kerry & Dingle Peninsula (Southwest)',
      highLow: '14°C / 9°C (57°F / 48°F)',
      conditions: 'Mild maritime breeze, lush humidity, damp mountain passes',
      outfitRecommendation: 'Waterproof trail boots, packable rain jacket, layered sweater, casual pub evening wear.'
    },
    {
      region: 'Dublin & East Coast (Navan / Kilkenny)',
      highLow: '15°C / 7°C (59°F / 45°F)',
      conditions: 'Driest region, crisp autumn evenings, cool mornings',
      outfitRecommendation: 'Smart casual layers, stylish walking boots/sneakers, warm coat for pub crawl, formal dinner attire for Mister S.'
    }
  ],
  dailyForecast: [
    { date: 'Oct 2 (Fri)', region: 'Northern Ireland', tempHigh: '13°C / 55°F', tempLow: '7°C / 45°F', rainProb: '40%', wind: '20 km/h', icon: '🌦️', condition: 'Passing showers & sun breaks', outfit: 'Layered travel wear, waterproof jacket for arrival & walk' },
    { date: 'Oct 3 (Sat)', region: 'Northern Ireland', tempHigh: '14°C / 57°F', tempLow: '8°C / 46°F', rainProb: '30%', wind: '18 km/h', icon: '⛅', condition: 'Partly sunny & crisp', outfit: 'Smart casual city layers, comfortable walking shoes for Belfast & Titanic' },
    { date: 'Oct 4 (Sun)', region: 'Northern Ireland', tempHigh: '12°C / 54°F', tempLow: '6°C / 43°F', rainProb: '55%', wind: '35 km/h', icon: '💨', condition: 'Windy with coastal squalls', outfit: 'Heavy windproof shell, thermal base, hiking boots, warm hat for Giant’s Causeway' },
    { date: 'Oct 5 (Mon)', region: 'Galway / West', tempHigh: '14°C / 57°F', tempLow: '8°C / 46°F', rainProb: '50%', wind: '25 km/h', icon: '🌧️', condition: 'Atlantic rain bands & breezy', outfit: 'Comfortable road-trip clothes, waterproof jacket for Galway City walk' },
    { date: 'Oct 6 (Tue)', region: 'Galway / Clare', tempHigh: '13°C / 55°F', tempLow: '7°C / 45°F', rainProb: '45%', wind: '40 km/h', icon: '💨', condition: 'High winds on coastal cliffs', outfit: 'NO UMBRELLAS. Windbreaker hooded jacket, sturdy boots, fleece for Cliffs of Moher' },
    { date: 'Oct 7 (Wed)', region: 'Galway / Connemara', tempHigh: '12°C / 54°F', tempLow: '6°C / 43°F', rainProb: '60%', wind: '22 km/h', icon: '🌦️', condition: 'Damp mist & mountain showers', outfit: 'Waterproof hiking pants & jacket, high-traction boots for Diamond Hill hike' },
    { date: 'Oct 8 (Thu)', region: 'Kerry / Killarney', tempHigh: '14°C / 57°F', tempLow: '9°C / 48°F', rainProb: '35%', wind: '18 km/h', icon: '⛅', condition: 'Mild with sunny intervals', outfit: 'Midweight fleece, water-resistant shoes, casual dinner outfit for Cronins' },
    { date: 'Oct 9 (Fri)', region: 'Kerry / Dingle', tempHigh: '13°C / 55°F', tempLow: '8°C / 46°F', rainProb: '50%', wind: '32 km/h', icon: '🌊', condition: 'Ocean breeze & scenic squalls', outfit: 'Windproof outer shell, knit beanie, wool socks, smart casual for Mad Monk dinner' },
    { date: 'Oct 10 (Sat)', region: 'Kerry / Dunloe', tempHigh: '14°C / 57°F', tempLow: '7°C / 45°F', rainProb: '25%', wind: '14 km/h', icon: '🌤️', condition: 'Bright & pleasant autumn day', outfit: 'Light hiking layers, trail boots for Gap of Dunloe & Strickeen Mountain' },
    { date: 'Oct 11 (Sun)', region: 'Dublin / Kilkenny', tempHigh: '15°C / 59°F', tempLow: '8°C / 46°F', rainProb: '30%', wind: '16 km/h', icon: '⛅', condition: 'Crisp autumn sunshine', outfit: 'Comfortable travel attire, warm sweater for Rock of Cashel & Kilkenny Castle' },
    { date: 'Oct 12 (Mon)', region: 'Dublin / Boyne', tempHigh: '14°C / 57°F', tempLow: '6°C / 43°F', rainProb: '20%', wind: '15 km/h', icon: '☀️', condition: 'Clear morning, cool night', outfit: 'Smart casual layers for 10:30 AM Guinness Tour & evening Dublin pub crawl' },
    { date: 'Oct 13 (Tue)', region: 'Dublin City', tempHigh: '15°C / 59°F', tempLow: '8°C / 46°F', rainProb: '25%', wind: '18 km/h', icon: '🎂', condition: 'Mild & celebration ready!', outfit: 'Day: Casual chic for brunch/shopping. Night: FANCY FORMAL / COCKTAIL for Mister S!' },
    { date: 'Oct 14 (Wed)', region: 'Dublin Airport', tempHigh: '13°C / 55°F', tempLow: '7°C / 45°F', rainProb: '35%', wind: '20 km/h', icon: '🛫', condition: 'Cool breeze & scattered clouds', outfit: 'Comfortable airport & airplane layers' }
  ]
};

// ── Outfits & Packing Guidelines ─────────────────────────────
const outfitGuides = [
  {
    category: 'Wild Coastal Cliffs & Bluffs',
    locations: 'Cliffs of Moher, Giant’s Causeway, Slea Head Drive, Carrick-a-Rede',
    icon: '🌊',
    essentials: [
      'Hooded Waterproof & Windproof Shell (Gore-Tex / DWR 15,000mm+)',
      'Thermal/Merino Base Layer (traps warmth, wicks sweat)',
      'Fleece or Packable Down Mid-Layer',
      'Wind-resistant Hiking Pants (Quick-dry; avoid heavy denim)',
      'Broken-in Waterproof Hiking Boots with deep rubber tread',
      'Fleece Beanie / Earband & Neck Gaiter (winds exceed 40 km/h)',
      '⚠️ Note: Do NOT use umbrellas near cliff edges — gale gusts will turn them inside out!'
    ]
  },
  {
    category: 'Mountain Trails & Bog Hikes',
    locations: 'Diamond Hill (Connemara), Gap of Dunloe, Strickeen Mountain, Slieve Gullion',
    icon: '🥾',
    essentials: [
      'High-ankle waterproof hiking boots (muddy & rocky terrain)',
      'Packable lightweight rain pants in backpack',
      'Breathable moisture-wicking athletic layers',
      'Merino wool hiking socks (plus an extra dry pair in daypack)',
      'Lightweight trekking poles (helpful for rocky descents)',
      'Waterproof daypack or dry sack for phone/cameras'
    ]
  },
  {
    category: 'City Walking & Historic Pub Crawls',
    locations: 'Belfast Cathedral Quarter, Galway Latin Quarter, Dublin Temple Bar, Kilkenny',
    icon: '🏙️',
    essentials: [
      'Smart casual dark jeans or chinos',
      'Stylish water-resistant leather sneakers or Chelsea boots',
      'Waxed cotton jacket or stylish wool overcoat',
      'Layerable knit sweaters or henleys (pubs are warm and cozy inside)',
      'Compact wind-resistant umbrella for city streets'
    ]
  },
  {
    category: "Dad & Erin's Birthday Celebration Dinner",
    locations: 'Ruibin / Dough Bros (Galway) — Oct 7 (Wed)',
    icon: '🎂',
    essentials: [
      'Smart casual / celebratory dinner wear',
      'Clean button-down or knit sweater with chinos/jeans',
      'Comfortable dress shoes or clean leather boots for Galway cobblestones',
      'Warm jacket for walking between Latin Quarter venues'
    ]
  },
  {
    category: "Mom's Premier Birthday Dinner",
    locations: 'Mister S (Camden St, Dublin) — Oct 13 (Tue)',
    icon: '🎂',
    essentials: [
      'Formal / Cocktail / Semi-Formal Dress Code',
      'Ladies: Elegant dinner dress, stylish jumpsuit, or chic blazer + trousers, dress heels/flats',
      'Gentlemen: Tailored blazer/sport coat, collared button-down shirt, dress trousers, leather dress shoes',
      'Warm wrap / coat for walking from vehicle to venue'
    ]
  }
];

// ── Hiking & Nature Locations (with Matching Statuses) ───────
const hikingTrails = [
  {
    name: "Giant's Causeway Cliff Top & Causeway Walk",
    region: 'ni',
    regionName: 'Northern Ireland',
    base: 'Walnut Retreat (Newry)',
    status: 'Planned',
    difficulty: 'Moderate',
    distance: '8.0 km / 5.0 mi',
    duration: '2.5–3.0 hrs',
    elevGain: '+160 m / 525 ft',
    surface: 'Basalt hexagonal steps, gravel path, cliff staircase',
    gear: 'Waterproof hiking boots, windshell, beanie',
    highlights: '40,000 interlocking volcanic basalt columns, Shepherd’s Steps, Amphitheatre, Atlantic ocean views',
    weatherAlert: 'Exposed to North Atlantic gales. High-traction boots mandatory on wet basalt.',
    linkAttraction: 'Giants Causeway'
  },
  {
    name: 'Carrick-a-Rede Rope Bridge Coastal Path',
    region: 'ni',
    regionName: 'Northern Ireland',
    base: 'Walnut Retreat (Newry)',
    status: 'Planned',
    difficulty: 'Easy–Moderate',
    distance: '2.0 km / 1.2 mi',
    duration: '1.0–1.5 hrs',
    elevGain: '+65 m / 213 ft',
    surface: 'Paved & stepped coastal trail, swinging rope bridge',
    gear: 'Sturdy walking shoes, windbreaker',
    highlights: 'Suspended rope bridge 100ft above roaring ocean, bird cliffs, Sheep Island views',
    weatherAlert: 'Bridge closes during winds > 35 knots (40 mph).',
    linkAttraction: 'Carrick-a-Rede Rope Bridge'
  },
  {
    name: 'Slieve Gullion Forest & South Cairn Passage Tomb',
    region: 'ni',
    regionName: 'Northern Ireland',
    base: 'Walnut Retreat (Newry)',
    status: 'Optional',
    difficulty: 'Moderate',
    distance: '4.5 km / 2.8 mi',
    duration: '2.0 hrs',
    elevGain: '+290 m / 950 ft',
    surface: 'Forest road, gravel mountain trail, stone steps',
    gear: 'Trail runners or hiking boots, fleece layer',
    highlights: 'Highest peak in County Armagh, Neolithic passage tomb (Calliagh Birra’s House), Ring of Gullion AONB',
    weatherAlert: 'Mist can settle quickly on summit cairn.',
    linkAttraction: 'Slieve Gullion Forest'
  },
  {
    name: 'Kilbroney Park & Cloughmore Stone Viewpoint',
    region: 'ni',
    regionName: 'Northern Ireland',
    base: 'Walnut Retreat (Newry)',
    status: 'Planned',
    difficulty: 'Easy–Moderate',
    distance: '3.5 km / 2.2 mi',
    duration: '1.5 hrs',
    elevGain: '+210 m / 690 ft',
    surface: 'Graded forest tracks and viewpoint boardwalk',
    gear: 'Comfortable walking shoes/sneakers, light jacket',
    highlights: 'Massive 50-ton glacial erratic granite boulder, panoramic vistas over Carlingford Lough and Mournes',
    weatherAlert: 'Pleasant wooded shelter from strong winds.',
    linkAttraction: 'Kilbroney Park Forest'
  },
  {
    name: 'Cliffs of Moher Coastal Cliff Path',
    region: 'galway',
    regionName: 'Galway / Clare',
    base: 'Spiddal Villa (Galway)',
    status: 'Confirmed',
    difficulty: 'Moderate',
    distance: '8.5 km / 5.3 mi (Flexible)',
    duration: '2.0–3.0 hrs',
    elevGain: '+120 m / 395 ft',
    surface: 'Exposed dirt path, stone flagstones, clifftop edges',
    gear: 'Ankle-supporting waterproof boots, heavy windbreaker (NO umbrellas)',
    highlights: '702ft sheer ocean drop, O’Brien’s Tower, Aran Islands silhouettes, seabird nesting colonies',
    weatherAlert: 'Severe wind hazard. Always stay behind official safety barrier flagstones.',
    linkAttraction: 'Cliffs of Moher'
  },
  {
    name: 'Diamond Hill Upper & Lower Trail (Connemara National Park)',
    region: 'galway',
    regionName: 'Galway / Connemara',
    base: 'Spiddal Villa (Galway)',
    status: 'Confirmed',
    difficulty: 'Moderate–Strenuous',
    distance: '7.0 km / 4.3 mi',
    duration: '2.5–3.0 hrs',
    elevGain: '+400 m / 1,312 ft',
    surface: 'Timber boardwalk, stepped rocky ascent, stone ridge',
    gear: 'High-traction waterproof hiking boots, rain pants, windshell, water',
    highlights: '360° summit views over Kylemore Abbey turret, Ballynakill Harbour, and the rugged Twelve Bens peaks',
    weatherAlert: 'Exposed rocky ridge near summit. Wet rock can be slippery.',
    linkAttraction: 'Connemara National Park'
  },
  {
    name: 'The Burren Karst Limestone & Mullaghmore Loop',
    region: 'galway',
    regionName: 'Galway / Clare',
    base: 'Spiddal Villa (Galway)',
    status: 'Planned',
    difficulty: 'Easy–Moderate',
    distance: '5.0 km / 3.1 mi',
    duration: '2.0 hrs',
    elevGain: '+140 m / 460 ft',
    surface: 'Limestone pavement (clints & grykes), loose stone',
    gear: 'Stiff-soled hiking boots with deep ankle support',
    highlights: 'Otherworldly moonscape karst terrain, unique arctic-alpine flora growing between rock fissures, ancient stone walls',
    weatherAlert: 'Watch foot placement on wet limestone grykes.',
    linkAttraction: 'Burren National Park'
  },
  {
    name: 'Gap of Dunloe Glacial Mountain Pass',
    region: 'kerry',
    regionName: 'Kerry / Killarney',
    base: 'Milltown House (Killarney)',
    status: 'Confirmed',
    difficulty: 'Moderate',
    distance: '10.5 km / 6.5 mi (or partial)',
    duration: '3.0–3.5 hrs',
    elevGain: '+220 m / 720 ft',
    surface: 'Narrow mountain road, historic stone bridges, lakeside path',
    gear: 'Walking shoes or boots, light rain layer, camera',
    highlights: 'Wishing Bridge, five glacial lakes, soaring cliffs between Purple Mountain and MacGillycuddy’s Reeks',
    weatherAlert: 'Share path with occasional jaunting pony carts.',
    linkAttraction: 'Gap of Dunloe'
  },
  {
    name: 'Strickeen Mountain Summit Hike',
    region: 'kerry',
    regionName: 'Kerry / Killarney',
    base: 'Milltown House (Killarney)',
    status: 'Optional',
    difficulty: 'Moderate–Strenuous',
    distance: '6.0 km / 3.7 mi',
    duration: '2.5 hrs',
    elevGain: '+340 m / 1,115 ft',
    surface: 'Rocky mountain track, grassy peat bog path',
    gear: 'Waterproof hiking boots with ankle support, trekking poles, warm mid-layer',
    highlights: 'Spectacular front-row panorama of Carrauntoohil (Ireland’s highest mountain) and Killarney valley',
    weatherAlert: 'Boggy sections after autumn rainfall.',
    linkAttraction: 'Strickeen Mountain'
  },
  {
    name: 'Torc Waterfall & Torc Mountain Boardwalk Trail',
    region: 'kerry',
    regionName: 'Kerry / Killarney',
    base: 'Milltown House (Killarney)',
    status: 'Confirmed',
    difficulty: 'Easy to Waterfall / Moderate to Summit',
    distance: '4.0 km / 2.5 mi',
    duration: '1.5–2.0 hrs',
    elevGain: '+260 m / 850 ft',
    surface: 'Wooden railway sleeper steps, stone steps, forest floor',
    gear: 'Waterproof shoes/boots, light layers',
    highlights: 'Roaring 66ft cascading waterfall surrounded by mossy woodlands, upper lake viewpoints',
    weatherAlert: 'Boardwalk sleepers have wire mesh for grip, but step carefully.',
    linkAttraction: 'Torc Waterfall'
  },
  {
    name: 'Muckross Abbey & Lake Muckross Peninsula Loop',
    region: 'kerry',
    regionName: 'Kerry / Killarney',
    base: 'Milltown House (Killarney)',
    status: 'Confirmed',
    difficulty: 'Easy',
    distance: '5.5 km / 3.4 mi',
    duration: '1.5 hrs',
    elevGain: '+35 m / 115 ft',
    surface: 'Paved and smooth gravel estate walking paths',
    gear: 'Comfortable sneakers or walking shoes',
    highlights: '15th-century Franciscan abbey cloister with ancient yew tree, wild native red deer grazing on estate lawns',
    weatherAlert: 'Flat, well-drained trails suitable in all weather.',
    linkAttraction: 'Muckross Abbey'
  },
  {
    name: 'Slea Head & Dunmore Head Coastal Bluffs Walk',
    region: 'kerry',
    regionName: 'Kerry / Dingle',
    base: 'Milltown House (Killarney)',
    status: 'Confirmed',
    difficulty: 'Easy–Moderate',
    distance: '3.0 km / 1.9 mi',
    duration: '1.0 hr',
    elevGain: '+90 m / 295 ft',
    surface: 'Grassy coastal cliff paths, beach trail',
    gear: 'Windproof shell, sturdy shoes, camera',
    highlights: 'Westernmost point of mainland Ireland, Blasket Islands vista, Star Wars filming location, dramatic breakers',
    weatherAlert: 'Strong ocean headwinds common.',
    linkAttraction: 'Slea Head Drive'
  },
  {
    name: 'Boyne Valley Historic River Trail & Newgrange Grounds',
    region: 'dublin',
    regionName: 'Dublin / Meath',
    base: 'Navan Home (Dublin area)',
    status: 'Confirmed',
    difficulty: 'Easy',
    distance: '4.0 km / 2.5 mi',
    duration: '1.5 hrs',
    elevGain: '+40 m / 130 ft',
    surface: 'Maintained gravel path, grass lawns',
    gear: 'Comfortable walking shoes, warm jacket',
    highlights: '5,200-year-old Stone Age megasite, River Boyne pastoral scenery',
    weatherAlert: 'Open countryside paths, bring light rain jacket.',
    linkAttraction: 'Newgrange Monument'
  }
];

// ── Day-by-day Rich Schedule with Blocked Time Ranges ──────────
const timeline = [
  {
    dayNumber: 1,
    date: 'Oct 2 (Fri)',
    region: 'ni',
    color: '#10b981',
    title: 'Arrival Day & Check-in Walnut Retreat',
    base: 'Walnut Retreat (Newry)',
    route: 'Dublin Airport → Newry → Belfast → Newry',
    isTransfer: true,
    driveHours: 3.0,
    special: false,
    weather: '🌦️ 13°C / 55°F · Passing showers & crisp air',
    outfit: '👟 Layered travel wear + packable rain jacket for fresh air walk',
    budget: { driving: 3.0, sightseeing: 4.5, dining: 3.0, free: 0.5 },
    items: [
      { time: '8:25 AM – 9:45 AM', startHour: 8.4, endHour: 9.75, dur: '1.25h', activity: '🛬 Arrive Dublin Airport & Baggage', type: 'sight', anchor: true, tag: 'FLIGHT ARRIVAL', desc: 'Land in Dublin, pass passport control, collect luggage and retrieve rental vehicle.' },
      { time: '10:00 AM – 11:30 AM', startHour: 10.0, endHour: 11.5, dur: '1.5h', activity: '🚗 Drive to Newry Base', type: 'drive', tag: 'DRIVE', desc: '100 km / 62 mi highway drive up the M1/A1 corridor.' },
      { time: '11:30 AM – 12:00 PM', startHour: 11.5, endHour: 12.0, dur: '30m', activity: '🏡 Check in Walnut Retreat', type: 'housing', tag: 'HOUSING WINDOW', desc: 'Unload bags, settle in at base #1 (Newry).' },
      { time: '12:00 PM – 2:00 PM', startHour: 12.0, endHour: 14.0, dur: '2h', activity: '🍽️ Lunch & Town Orientation', type: 'dining', tag: 'CASUAL MEAL', desc: 'Casual lunch in Newry (The Diner or Cozy Corner).' },
      { time: '2:00 PM – 4:30 PM', startHour: 14.0, endHour: 16.5, dur: '2.5h', activity: '🌳 Kilbroney Park or Slieve Gullion Forest', type: 'sight', tag: 'NATURE WALK', desc: 'Fresh air walk, scenic viewpoint overlooking Carlingford Lough.' },
      { time: '5:00 PM – 6:00 PM', startHour: 17.0, endHour: 18.0, dur: '1h', activity: "🏰 Bagenal's Castle (Newry)", type: 'sight', tag: 'HISTORY', desc: '16th-century fortified tower house & museum in downtown Newry.' },
      { time: '6:00 PM – 7:00 PM', startHour: 18.0, endHour: 19.0, dur: '1h', activity: '🚗 Drive Newry → Belfast', type: 'drive', tag: 'DRIVE', desc: 'Drive 39 mi north to Belfast for dinner.' },
      { time: '7:00 PM – 9:00 PM', startHour: 19.0, endHour: 21.0, dur: '2h', activity: '🍽️ Holohans Pantry Dinner (Belfast)', type: 'dining', reserved: true, tag: 'CONFIRMED RESERVATION', note: '48hr cancellation window', desc: 'Reserved table for 7:00 PM. Famous traditional Irish boxty & seafood.' },
      { time: '9:00 PM – 10:00 PM', startHour: 21.0, endHour: 22.0, dur: '1h', activity: '🚗 Return Drive to Newry Base', type: 'drive', tag: 'DRIVE', desc: 'Return drive back to Walnut Retreat.' },
    ],
  },
  {
    dayNumber: 2,
    date: 'Oct 3 (Sat)',
    region: 'ni',
    color: '#10b981',
    title: 'Belfast City & Titanic History',
    base: 'Walnut Retreat (Newry)',
    route: 'Newry → Belfast → Dundrum → Newry',
    isTransfer: false,
    driveHours: 2.5,
    special: false,
    weather: '⛅ 14°C / 57°F · Partly sunny & brisk',
    outfit: '🏙️ Smart casual city layers, comfortable walking shoes, light jacket',
    budget: { driving: 2.5, sightseeing: 6.0, dining: 3.0, free: 0.5 },
    items: [
      { time: '8:00 AM – 9:00 AM', startHour: 8.0, endHour: 9.0, dur: '1h', activity: '☕ Breakfast (Cozy Corner, Newry)', type: 'dining', tag: 'BREAKFAST', desc: 'Full Irish breakfast before heading to Belfast.' },
      { time: '9:00 AM – 10:00 AM', startHour: 9.0, endHour: 10.0, dur: '1h', activity: '🚗 Drive Newry → Belfast Titanic Quarter', type: 'drive', tag: 'DRIVE', desc: 'Direct route on A1/M1 into Belfast.' },
      { time: '10:00 AM – 12:30 PM', startHour: 10.0, endHour: 12.5, dur: '2.5h', activity: '🚢 Titanic Belfast Experience', type: 'sight', tag: 'PLANNED VISIT', desc: 'World-leading maritime museum on the slipways where Titanic was built.' },
      { time: '12:30 PM – 1:00 PM', startHour: 12.5, endHour: 13.0, dur: '30m', activity: "⛪ St. Anne's Cathedral (Cathedral Quarter)", type: 'sight', tag: 'CULTURE', desc: 'Walk through Belfast Cathedral Quarter.' },
      { time: '1:00 PM – 2:00 PM', startHour: 13.0, endHour: 14.0, dur: '1h', activity: '🍽️ Lunch: Common Market / Stacked', type: 'dining', tag: 'LUNCH', desc: 'Artisan food court with various gourmet stalls.' },
      { time: '2:00 PM – 3:30 PM', startHour: 14.0, endHour: 15.5, dur: '1.5h', activity: '🧱 Peace Wall + Black Cab History Tour', type: 'sight', tag: 'GUIDED TOUR', desc: 'Guided black cab tour through Falls Road & Shankill Road murals.' },
      { time: '3:30 PM – 5:00 PM', startHour: 15.5, endHour: 17.0, dur: '1.5h', activity: "🛒 St. George's Market & City Centre Walk", type: 'sight', tag: 'EXPLORE', desc: 'Victorian covered market and downtown walking.' },
      { time: '5:00 PM – 6:15 PM', startHour: 17.0, endHour: 18.25, dur: '1.25h', activity: '🍺 Duke of York / Bittles Bar', type: 'dining', tag: 'PUB STOP', desc: 'Cobblestone alleyway pint in iconic Cathedral Quarter pub.' },
      { time: '6:15 PM – 7:15 PM', startHour: 18.25, endHour: 19.25, dur: '1h', activity: '🚗 Drive Belfast → Dundrum', type: 'drive', tag: 'DRIVE', desc: 'Drive down to the coast for seafood.' },
      { time: '7:15 PM – 9:00 PM', startHour: 19.25, endHour: 21.0, dur: '1.75h', activity: '🦞 Mourne Seafood Dinner (Dundrum)', type: 'dining', reserved: true, tag: 'TENTATIVE RESERVATION', desc: 'Fresh seafood straight from local Mourne coastal waters.' },
      { time: '9:00 PM – 9:45 PM', startHour: 21.0, endHour: 21.75, dur: '45m', activity: '🚗 Return Drive to Newry Base', type: 'drive', tag: 'DRIVE', desc: 'Quick 35 min return to Walnut Retreat.' },
    ],
  },
  {
    dayNumber: 3,
    date: 'Oct 4 (Sun)',
    region: 'ni',
    color: '#10b981',
    title: 'Causeway Coast & Giant’s Causeway',
    base: 'Walnut Retreat (Newry)',
    route: 'Newry → Causeway → Bushmills → Carrick-a-Rede → Newry',
    isTransfer: false,
    driveHours: 5.0,
    special: false,
    weather: '💨 12°C / 54°F · Windy (35 km/h) with coastal sea squalls',
    outfit: '🥾 Heavy windproof Gore-Tex shell, thermal layers, hiking boots with grip, beanie',
    budget: { driving: 5.0, sightseeing: 5.0, dining: 3.0, free: 0.0 },
    note: '⚠️ Heavy driving day (5h total in car). Pace stops based on weather.',
    items: [
      { time: '7:30 AM – 8:15 AM', startHour: 7.5, endHour: 8.25, dur: '45m', activity: '☕ Early Breakfast at Base', type: 'dining', tag: 'BREAKFAST', desc: 'Fuel up for the longest day trip up north.' },
      { time: '8:15 AM – 10:30 AM', startHour: 8.25, endHour: 10.5, dur: '2.25h', activity: '🚗 Drive Newry → Giants Causeway', type: 'drive', tag: 'LONG DRIVE', desc: 'Scenic route heading north across Antrim.' },
      { time: '10:30 AM – 12:30 PM', startHour: 10.5, endHour: 12.5, dur: '2h', activity: '🪨 Giant’s Causeway UNESCO Site', type: 'sight', tag: 'COASTAL HIKE', desc: '40,000 interlocking basalt columns created by ancient volcanic action.' },
      { time: '12:30 PM – 1:00 PM', startHour: 12.5, endHour: 13.0, dur: '30m', activity: '🚗 Drive to Bushmills', type: 'drive', tag: 'DRIVE', desc: 'Quick 10-minute jump to neighboring town.' },
      { time: '1:00 PM – 2:30 PM', startHour: 13.0, endHour: 14.5, dur: '1.5h', activity: '🥃 Old Bushmills Distillery + Lunch', type: 'sight', tag: 'TASTING & LUNCH', desc: "World's oldest licensed whiskey distillery (1608) and lunch stop." },
      { time: '2:30 PM – 3:00 PM', startHour: 14.5, endHour: 15.0, dur: '30m', activity: '🚗 Drive to Carrick-a-Rede', type: 'drive', tag: 'DRIVE', desc: 'Coastal drive east towards the rope bridge.' },
      { time: '3:00 PM – 4:15 PM', startHour: 15.0, endHour: 16.25, dur: '1.25h', activity: '🌉 Carrick-a-Rede Rope Bridge', type: 'sight', tag: 'COASTAL WALK', desc: 'Rope bridge walk 100ft above the crashing waves (weather permitting).' },
      { time: '4:15 PM – 6:45 PM', startHour: 16.25, endHour: 18.75, dur: '2.5h', activity: '🚗 Coastal Causeway Drive Return', type: 'drive', tag: 'SCENIC DRIVE', desc: 'Stunning drive through the Glens of Antrim (Glenariff & Glenarm) back to Newry.' },
      { time: '7:00 PM – 9:00 PM', startHour: 19.0, endHour: 21.0, dur: '2h', activity: '🍽️ Dinner: The Oliver / Bellinis (Newry)', type: 'dining', tag: 'DINNER', desc: 'Relaxing dinner in town near our house.' },
    ],
  },
  {
    dayNumber: 4,
    date: 'Oct 5 (Mon)',
    region: 'galway',
    color: '#3b82f6',
    title: 'Base Transfer: Newry → Spiddal (Galway)',
    base: 'Spiddal Villa (Galway)',
    route: 'Newry → Galway City → Spiddal',
    isTransfer: true,
    driveHours: 4.0,
    special: false,
    weather: '🌧️ 14°C / 57°F · Atlantic rain bands & breezy',
    outfit: '🚗 Stretchy travel clothes + waterproof jacket for Latin Quarter walk',
    budget: { driving: 4.0, sightseeing: 3.0, dining: 3.0, free: 1.0 },
    items: [
      { time: '8:00 AM – 9:00 AM', startHour: 8.0, endHour: 9.0, dur: '1h', activity: '☕ Breakfast & Luggage Packing', type: 'free', tag: 'PACKING', desc: 'Pack all bags and tidy Walnut Retreat.' },
      { time: '9:00 AM – 9:15 AM', startHour: 9.0, endHour: 9.25, dur: '15m', activity: '🏡 Check out Walnut Retreat', type: 'housing', tag: 'CHECK-OUT', note: 'Check-out window by 11 AM', desc: 'Hand over keys and depart Northern Ireland.' },
      { time: '9:15 AM – 1:00 PM', startHour: 9.25, endHour: 13.0, dur: '3.75h', activity: '🚗 BASE TRANSFER: Newry → Galway', type: 'drive', tag: 'BASE MOVE', desc: '250 km / 155 mi cross-country drive from east coast to west coast (M1/M6).' },
      { time: '1:00 PM – 2:00 PM', startHour: 13.0, endHour: 14.0, dur: '1h', activity: '🍽️ Lunch in Galway City', type: 'dining', tag: 'LUNCH', desc: 'Grab lunch upon arriving in Galway.' },
      { time: '2:00 PM – 3:30 PM', startHour: 14.0, endHour: 15.5, dur: '1.5h', activity: '🏙️ Explore Galway Latin Quarter & Quays', type: 'sight', tag: 'EXPLORE', desc: 'Vibrant street musicians, Spanish Arch, colorful shops on Quay St.' },
      { time: '3:30 PM – 4:00 PM', startHour: 15.5, endHour: 16.0, dur: '30m', activity: '🚗 Drive Galway → Spiddal Coast', type: 'drive', tag: 'DRIVE', desc: 'Coastal drive into the Gaeltacht village of Spiddal.' },
      { time: '4:00 PM – 4:30 PM', startHour: 16.0, endHour: 16.5, dur: '30m', activity: '🏡 Check in Spiddal Villa', type: 'housing', tag: 'CHECK-IN', desc: 'Check in to Base #2 (Spiddal Villa) overlooking Galway Bay.' },
      { time: '4:30 PM – 6:00 PM', startHour: 16.5, endHour: 18.0, dur: '1.5h', activity: '🌊 Spiddal Beach Walk & Relax', type: 'free', tag: 'COASTAL WALK', desc: 'Spiddal craft village, pier, and rocky Atlantic beach.' },
      { time: '7:00 PM – 9:00 PM', startHour: 19.0, endHour: 21.0, dur: '2h', activity: '🍽️ Dinner: Donnellys of Barna', type: 'dining', tag: 'DINNER', desc: 'Historic 1892 pub with seafood overlooking the harbor.' },
    ],
  },
  {
    dayNumber: 5,
    date: 'Oct 6 (Tue)',
    region: 'galway',
    color: '#3b82f6',
    title: 'Cliffs of Moher & The Burren',
    base: 'Spiddal Villa (Galway)',
    route: 'Spiddal → Cliffs of Moher → Burren → Dunguaire → Spiddal',
    isTransfer: false,
    driveHours: 3.5,
    special: false,
    weather: '💨 13°C / 55°F · High coastal winds (40 km/h) & passing squalls',
    outfit: '🌊 Heavy hooded windbreaker, thermal base, hiking boots, warm socks. NO UMBRELLAS',
    budget: { driving: 3.5, sightseeing: 5.25, dining: 3.0, free: 0.25 },
    items: [
      { time: '8:00 AM – 9:00 AM', startHour: 8.0, endHour: 9.0, dur: '1h', activity: '☕ Breakfast at Spiddal Villa', type: 'dining', tag: 'BREAKFAST', desc: 'Breakfast with ocean view.' },
      { time: '9:00 AM – 10:15 AM', startHour: 9.0, endHour: 10.25, dur: '1.25h', activity: '🚗 Drive Spiddal → Cliffs of Moher', type: 'drive', tag: 'DRIVE', desc: 'Drive south around Galway Bay into County Clare.' },
      { time: '10:15 AM – 12:30 PM', startHour: 10.25, endHour: 12.5, dur: '2.25h', activity: '🏔️ Cliffs of Moher Coastal Walk', type: 'sight', tag: 'HIGHLIGHT', desc: 'Towering 700ft cliffs over the wild Atlantic ocean & O’Brien’s Tower.' },
      { time: '12:30 PM – 1:30 PM', startHour: 12.5, endHour: 13.5, dur: '1h', activity: '🚗 Drive through Burren + Pub Lunch', type: 'dining', tag: 'LUNCH', desc: 'Stop in Ballyvaughan or Doolin for seafood chowder.' },
      { time: '1:30 PM – 3:30 PM', startHour: 13.5, endHour: 15.5, dur: '2h', activity: '🪨 Burren National Park Glaciated Karst', type: 'sight', tag: 'NATURE TRAIL', desc: 'Dramatic limestone pavement landscape with rare flora.' },
      { time: '3:30 PM – 4:15 PM', startHour: 15.5, endHour: 16.25, dur: '45m', activity: '🚗 Drive to Dunguaire Castle', type: 'drive', tag: 'DRIVE', desc: 'Drive to Kinvara on the edge of Galway Bay.' },
      { time: '4:15 PM – 5:15 PM', startHour: 16.25, endHour: 17.25, dur: '1h', activity: '🏰 Dunguaire Castle (Kinvara)', type: 'sight', tag: 'CASTLE', desc: '16th-century tower house rising dramatically from the bay.' },
      { time: '5:15 PM – 6:30 PM', startHour: 17.25, endHour: 18.5, dur: '1.25h', activity: '🚗 Return Drive to Spiddal + Freshen up', type: 'drive', tag: 'DRIVE', desc: 'Return to villa and get dressed for dinner.' },
      { time: '7:00 PM – 9:00 PM', startHour: 19.0, endHour: 21.0, dur: '2h', activity: '🍽️ Kirwans Seafood Dinner (Galway)', type: 'dining', reserved: true, tag: 'CONFIRMED RESERVATION', desc: 'Reserved table for 7:00 PM. High-end seafood restaurant in Latin Quarter.' },
    ],
  },
  {
    dayNumber: 6,
    date: 'Oct 7 (Wed)',
    region: 'galway',
    color: '#3b82f6',
    title: "Connemara & DAD & ERIN'S BIRTHDAY! 🎂🎂",
    base: 'Spiddal Villa (Galway)',
    route: 'Spiddal → Kylemore → Connemara NP → Spiddal → Galway Celebration',
    isTransfer: false,
    driveHours: 2.5,
    special: true,
    specialText: "DAD & ERIN'S BDAY 🎂",
    weather: '🎂 12°C / 54°F · Mountain mist & double birthday cheer',
    outfit: '🥾 Day: Hiking boots & layers for Diamond Hill. Evening: Smart casual celebration outfit for Dad & Erin!',
    budget: { driving: 2.5, sightseeing: 4.5, dining: 4.0, free: 1.0 },
    items: [
      { time: '8:00 AM – 9:00 AM', startHour: 8.0, endHour: 9.0, dur: '1h', activity: '☕ Birthday Morning Breakfast at Villa', type: 'dining', tag: 'BDAY MORNING', desc: 'Birthday coffee and treats with ocean view at Spiddal Villa.' },
      { time: '9:00 AM – 10:15 AM', startHour: 9.0, endHour: 10.25, dur: '1.25h', activity: '🚗 Drive Spiddal → Kylemore Abbey', type: 'drive', tag: 'DRIVE', desc: 'Wild Connemara bog and mountain driving via Maam Cross.' },
      { time: '10:15 AM – 12:15 PM', startHour: 10.25, endHour: 12.25, dur: '2h', activity: '🏰 Kylemore Abbey & Victorian Walled Garden', type: 'sight', tag: 'HISTORIC SITE', desc: 'Fairytale lakeside castle estate run by Benedictine nuns.' },
      { time: '12:15 PM – 1:00 PM', startHour: 12.25, endHour: 13.0, dur: '45m', activity: '🚗 Drive to Connemara NP (Letterfrack)', type: 'drive', tag: 'DRIVE', desc: 'Short drive to national park visitor center.' },
      { time: '1:00 PM – 2:00 PM', startHour: 13.0, endHour: 14.0, dur: '1h', activity: '🍽️ Birthday Picnic / Cafe Lunch', type: 'dining', tag: 'LUNCH', desc: 'Lunch at the national park tearoom / picnic area.' },
      { time: '2:00 PM – 4:30 PM', startHour: 14.0, endHour: 16.5, dur: '2.5h', activity: '🥾 Connemara NP Hike (Diamond Hill)', type: 'sight', tag: 'MOUNTAIN HIKE', desc: 'Panoramic summit views across the Twelve Bens mountain range and Atlantic.' },
      { time: '4:30 PM – 5:30 PM', startHour: 16.5, endHour: 17.5, dur: '1h', activity: '🚗 Return Drive to Spiddal', type: 'drive', tag: 'DRIVE', desc: 'Scenic mountain drive back to the house.' },
      { time: '5:30 PM – 7:00 PM', startHour: 17.5, endHour: 19.0, dur: '1.5h', activity: '🌅 Freshen Up for Birthday Celebration', type: 'free', anchor: true, tag: 'GET READY', desc: 'Unwind at the villa and get ready for Dad & Erin’s double birthday dinner.' },
      { time: '7:00 PM – 9:30 PM', startHour: 19.0, endHour: 21.5, dur: '2.5h', activity: '🎂🎂🍽️ DAD & ERIN’S BIRTHDAY DINNER', type: 'dining', reserved: true, anchor: true, tag: 'DOUBLE BDAY DINNER', desc: 'Special celebration dinner at Ruibin / Dough Bros in Galway with pints and wine toast!' },
      { time: '9:30 PM+', startHour: 21.5, endHour: 23.0, dur: '1.5h', activity: '🍻 Birthday Drinks & Trad Music in Galway / Spiddal', type: 'dining', tag: 'CELEBRATE', desc: 'Birthday cheers and live music session for Dad and Erin!' }
    ],
  },
  {
    dayNumber: 7,
    date: 'Oct 8 (Thu)',
    region: 'kerry',
    color: '#8b5cf6',
    title: 'Base Transfer: Galway → Killarney (Kerry)',
    base: 'Milltown House (Killarney)',
    route: 'Spiddal → Killarney/Milltown → Killarney NP',
    isTransfer: true,
    driveHours: 3.5,
    special: false,
    weather: '⛅ 14°C / 57°F · Mild & partly cloudy',
    outfit: '🚗 Travel layers + walking shoes for Ross Castle & Torc Waterfall; smart casual for Cronins',
    budget: { driving: 3.5, sightseeing: 3.5, dining: 3.0, free: 1.5 },
    items: [
      { time: '8:00 AM – 9:00 AM', startHour: 8.0, endHour: 9.0, dur: '1h', activity: '☕ Breakfast & Luggage Packing', type: 'free', tag: 'PACKING', desc: 'Pack luggage and check out of Spiddal Villa.' },
      { time: '9:00 AM – 9:15 AM', startHour: 9.0, endHour: 9.25, dur: '15m', activity: '🏡 Check out Spiddal Villa', type: 'housing', tag: 'CHECK-OUT', note: 'Check out window by 11 AM', desc: 'Depart Galway for the Kingdom of Kerry.' },
      { time: '9:15 AM – 12:00 PM', startHour: 9.25, endHour: 12.0, dur: '2.75h', activity: '🚗 BASE TRANSFER: Galway → Killarney', type: 'drive', tag: 'BASE MOVE', desc: '210 km / 130 mi drive south via Limerick / Shannon.' },
      { time: '12:00 PM – 12:30 PM', startHour: 12.0, endHour: 12.5, dur: '30m', activity: '🏡 Check in Milltown House (Killarney Base)', type: 'housing', tag: 'CHECK-IN', desc: 'Unpack at Base #3 (Milltown) near Killarney town.' },
      { time: '12:30 PM – 1:30 PM', startHour: 12.5, endHour: 13.5, dur: '1h', activity: "🍽️ Lunch (Matt the Millers / Quinlans)", type: 'dining', tag: 'LUNCH', desc: 'Crispy fish & chips in Killarney town.' },
      { time: '1:30 PM – 3:00 PM', startHour: 13.5, endHour: 15.0, dur: '1.5h', activity: '🏰 Ross Castle & Lough Leane Walk', type: 'sight', tag: 'CASTLE', desc: '15th-century O’Donoghue clan stronghold right on the lake.' },
      { time: '3:00 PM – 4:00 PM', startHour: 15.0, endHour: 16.0, dur: '1h', activity: '⛪ Muckross Abbey Ruins', type: 'sight', tag: 'RUINS', desc: 'Remarkably intact 1448 Franciscan friary with ancient yew tree.' },
      { time: '4:00 PM – 5:00 PM', startHour: 16.0, endHour: 17.0, dur: '1h', activity: '💧 Torc Waterfall Forest Walk', type: 'sight', tag: 'WATERFALL', desc: 'Spectacular 20m cascade surrounded by lush Kerry mosses.' },
      { time: '5:30 PM – 7:15 PM', startHour: 17.5, endHour: 19.25, dur: '1.75h', activity: '🛁 Rest & Freshen Up at Base', type: 'free', tag: 'FLEXIBLE TIME', desc: 'Shower and change for dinner reservation.' },
      { time: '7:30 PM – 9:30 PM', startHour: 19.5, endHour: 21.5, dur: '2h', activity: '🍽️ Cronins Restaurant Dinner', type: 'dining', reserved: true, tag: 'CONFIRMED RESERVATION', desc: 'Reserved table for 7:30 PM. Acclaimed traditional gastropub in Killarney.' },
    ],
  },
  {
    dayNumber: 8,
    date: 'Oct 9 (Fri)',
    region: 'kerry',
    color: '#8b5cf6',
    title: 'Dingle Peninsula & Slea Head Loop',
    base: 'Milltown House (Killarney)',
    route: 'Milltown → Dingle → Slea Head → Killarney',
    isTransfer: false,
    driveHours: 2.5,
    special: false,
    weather: '🌊 13°C / 55°F · Ocean breeze (32 km/h) & scenic bluffs',
    outfit: '🌊 Windproof jacket, warm sweater, comfortable shoes; nice casual for Mad Monk dinner',
    budget: { driving: 2.5, sightseeing: 5.0, dining: 3.0, free: 1.0 },
    items: [
      { time: '7:30 AM – 8:30 AM', startHour: 7.5, endHour: 8.5, dur: '1h', activity: '☕ Breakfast at House', type: 'dining', tag: 'BREAKFAST', desc: 'Quick breakfast before driving west to the Atlantic edge.' },
      { time: '8:30 AM – 9:45 AM', startHour: 8.5, endHour: 9.75, dur: '1.25h', activity: '🚗 Drive Killarney → Dingle Town', type: 'drive', tag: 'DRIVE', desc: 'Drive past Inch Beach along Dingle Bay.' },
      { time: '9:45 AM – 10:30 AM', startHour: 9.75, endHour: 10.5, dur: '45m', activity: '☕ Coffee & Harbor Walk in Dingle', type: 'dining', tag: 'HARBOR WALK', desc: 'Stroll around Dingle Marina and fishing boats.' },
      { time: '10:30 AM – 1:00 PM', startHour: 10.5, endHour: 13.0, dur: '2.5h', activity: '🏔️ Slea Head Coastal Drive & Beehive Huts', type: 'sight', tag: 'SCENIC DRIVE', desc: 'One of Europe’s most dramatic coastline drives looking out at Blasket Islands.' },
      { time: '1:00 PM – 2:00 PM', startHour: 13.0, endHour: 14.0, dur: '1h', activity: '🍽️ Lunch: Out of the Blue / Fishbox', type: 'dining', tag: 'LUNCH', desc: 'World-famous fresh catch of the day in Dingle.' },
      { time: '2:00 PM – 3:30 PM', startHour: 14.0, endHour: 15.5, dur: '1.5h', activity: '🏘️ Dick Macks Pub & Dingle Town Shops', type: 'sight', tag: 'PUB/CULTURE', desc: 'Legendary half-leather shop / half-whiskey pub.' },
      { time: '3:30 PM – 4:45 PM', startHour: 15.5, endHour: 16.75, dur: '1.25h', activity: '🚗 Drive Dingle → Killarney Base', type: 'drive', tag: 'DRIVE', desc: 'Return drive to Milltown House.' },
      { time: '4:45 PM – 5:45 PM', startHour: 16.75, endHour: 17.75, dur: '1h', activity: '🛁 Rest & Freshen Up for Dinner', type: 'free', tag: 'FLEXIBLE TIME', desc: 'Relax before the 6:00 PM booking.' },
      { time: '6:00 PM – 8:00 PM', startHour: 18.0, endHour: 20.0, dur: '2h', activity: '🍽️ Mad Monk Dinner (Killarney)', type: 'dining', reserved: true, tag: 'CONFIRMED RESERVATION', note: '48hr cancellation window', desc: 'Reserved table for 6:00 PM. High-end gourmet seafood bar & kitchen.' },
    ],
  },
  {
    dayNumber: 9,
    date: 'Oct 10 (Sat)',
    region: 'kerry',
    color: '#8b5cf6',
    title: 'Gap of Dunloe & Killarney National Park',
    base: 'Milltown House (Killarney)',
    route: 'Milltown → Gap of Dunloe → Killarney NP → Milltown',
    isTransfer: false,
    driveHours: 0.5,
    special: false,
    weather: '🌤️ 14°C / 57°F · Bright, crisp & best nature day',
    outfit: '🥾 Trail hiking boots, lightweight breathable layers, fleece for mountain pass',
    budget: { driving: 0.5, sightseeing: 6.5, dining: 3.0, free: 1.5 },
    note: '🌟 Lightest driving day of the entire trip (only 30m total). Pure nature.',
    items: [
      { time: '7:30 AM – 8:30 AM', startHour: 7.5, endHour: 8.5, dur: '1h', activity: '☕ Breakfast at House', type: 'dining', tag: 'BREAKFAST', desc: 'Hearty breakfast before mountain exploration.' },
      { time: '8:30 AM – 9:00 AM', startHour: 8.5, endHour: 9.0, dur: '30m', activity: '🚗 Drive to Kate Kearney’s Cottage', type: 'drive', tag: 'DRIVE', desc: 'Quick 20-minute drive to Gap of Dunloe entrance.' },
      { time: '9:00 AM – 12:00 PM', startHour: 9.0, endHour: 12.0, dur: '3h', activity: '⛰️ Gap of Dunloe Valley Pass & Strickeen', type: 'sight', tag: 'MOUNTAIN HIKE', desc: 'Narrow mountain pass carved by glaciers between MacGillycuddy’s Reeks.' },
      { time: '12:00 PM – 12:45 PM', startHour: 12.0, endHour: 12.75, dur: '45m', activity: '☕ Kate Kearney’s Pub Coffee & Snack', type: 'dining', tag: 'COFFEE', desc: 'Cozy pub stop at the foot of the mountain pass.' },
      { time: '12:45 PM – 2:00 PM', startHour: 12.75, endHour: 14.0, dur: '1.25h', activity: '🍽️ Lunch in Killarney', type: 'dining', tag: 'LUNCH', desc: 'Lunch at Tango or Matt the Millers.' },
      { time: '2:00 PM – 5:00 PM', startHour: 14.0, endHour: 17.0, dur: '3h', activity: '🌲 Deep Killarney National Park Trails', type: 'sight', tag: 'NATURE TRAIL', desc: 'Lakeside walks, native oak forests, and red deer spotting.' },
      { time: '5:00 PM – 7:00 PM', startHour: 17.0, endHour: 19.0, dur: '2h', activity: '🛁 Relax & Pack Ahead for Base Move', type: 'free', tag: 'FLEXIBLE TIME', desc: 'Free afternoon & pack some bags for the big move tomorrow.' },
      { time: '7:00 PM – 9:00 PM', startHour: 19.0, endHour: 21.0, dur: '2h', activity: '🍽️ Dinner: Hilliards / Mizu / JM Reidis', type: 'dining', tag: 'DINNER', desc: 'Vibrant dinner in Killarney town followed by traditional live session.' },
    ],
  },
  {
    dayNumber: 10,
    date: 'Oct 11 (Sun)',
    region: 'dublin',
    color: '#f59e0b',
    title: 'Base Transfer: Killarney → Kilkenny → Navan Home',
    base: 'Navan Home (Dublin area)',
    route: 'Killarney → Rock of Cashel → Kilkenny → Navan',
    isTransfer: true,
    driveHours: 4.5,
    special: false,
    weather: '⛅ 15°C / 59°F · Autumn sunshine & cool breeze',
    outfit: '🚗 Flexible driving clothes + walking shoes & jacket for Castle & Cashel',
    budget: { driving: 4.5, sightseeing: 3.5, dining: 3.0, free: 1.0 },
    note: '⚠️ Heavy transfer day across 3 counties. Check in at Navan after 3 PM.',
    items: [
      { time: '7:00 AM – 8:00 AM', startHour: 7.0, endHour: 8.0, dur: '1h', activity: '☕ Early Breakfast & Full Pack', type: 'free', tag: 'PACKING', desc: 'Early morning start for the longest transfer.' },
      { time: '8:00 AM – 8:15 AM', startHour: 8.0, endHour: 8.25, dur: '15m', activity: '🏡 Check out Milltown House', type: 'housing', tag: 'CHECK-OUT', note: 'Depart Kerry around 8:15 AM', desc: 'Hand in keys and begin eastbound journey.' },
      { time: '8:15 AM – 10:00 AM', startHour: 8.25, endHour: 10.0, dur: '1.75h', activity: '🚗 Drive Killarney → Rock of Cashel', type: 'drive', tag: 'TRANSFER LEG 1', desc: '143 km / 89 mi highway drive into Tipperary.' },
      { time: '10:00 AM – 11:00 AM', startHour: 10.0, endHour: 11.0, dur: '1h', activity: '⛪ Rock of Cashel Ancient Seat of Kings', type: 'sight', tag: 'HISTORIC SITE', desc: 'Spectacular medieval acropolis perched on limestone rock.' },
      { time: '11:00 AM – 12:00 PM', startHour: 11.0, endHour: 12.0, dur: '1h', activity: '🚗 Drive Cashel → Medieval Kilkenny', type: 'drive', tag: 'DRIVE', desc: '58 km / 36 mi scenic drive into County Kilkenny.' },
      { time: '12:00 PM – 1:00 PM', startHour: 12.0, endHour: 13.0, dur: '1h', activity: '🍽️ Lunch in Kilkenny Medieval Mile', type: 'dining', tag: 'LUNCH', desc: 'Traditional pub lunch on high street.' },
      { time: '1:00 PM – 2:30 PM', startHour: 13.0, endHour: 14.5, dur: '1.5h', activity: "🍺 Smithwick's Brewery Experience", type: 'sight', tag: 'TASTING', desc: "Interactive tour of Ireland's oldest red ale brewery (1710)." },
      { time: '2:30 PM – 3:30 PM', startHour: 14.5, endHour: 15.5, dur: '1h', activity: '🏰 Kilkenny Castle & Rose Gardens', type: 'sight', tag: 'CASTLE', desc: 'Stroll around the 12th-century Anglo-Norman fortress.' },
      { time: '3:30 PM – 5:15 PM', startHour: 15.5, endHour: 17.25, dur: '1.75h', activity: '🚗 Drive Kilkenny → Navan Home Base', type: 'drive', tag: 'TRANSFER LEG 2', desc: '128 km / 80 mi northward route on M9/M50 to Navan.' },
      { time: '5:15 PM – 6:00 PM', startHour: 17.25, endHour: 18.0, dur: '45m', activity: '🏡 Check in Navan Home', type: 'housing', tag: 'CHECK-IN', note: 'Check-in open after 3 PM', desc: 'Final base check-in (Navan house, 45m north of Dublin).' },
      { time: '6:00 PM – 7:30 PM', startHour: 18.0, endHour: 19.5, dur: '1.5h', activity: '🛁 Unpack & Settle In', type: 'free', tag: 'FLEXIBLE TIME', desc: 'Unpack luggage for our 3-night stay at the final house.' },
      { time: '7:30 PM – 9:30 PM', startHour: 19.5, endHour: 21.5, dur: '2h', activity: '🍽️ Dinner in Navan / Local Pub', type: 'dining', tag: 'DINNER', desc: 'Relaxed dinner in Navan before tomorrow’s early morning tour.' },
    ],
  },
  {
    dayNumber: 11,
    date: 'Oct 12 (Mon)',
    region: 'dublin',
    color: '#f59e0b',
    title: 'Guinness Storehouse (10:30 AM), Newgrange & Dublin Pub Crawl',
    base: 'Navan Home (Dublin area)',
    route: 'Navan → Dublin (Guinness 10:30 AM) → Boyne Valley (Newgrange) → Dublin (Pub Crawl) → Navan',
    isTransfer: false,
    driveHours: 2.25,
    special: false,
    weather: '☀️ 14°C / 57°F · Clear morning, brisk evening',
    outfit: '🍻 Smart casual layers for 10:30 AM Guinness Tour, comfortable shoes for pub crawl',
    budget: { driving: 2.25, sightseeing: 5.0, dining: 3.0, free: 0.75 },
    note: '🍺 10:30 AM Guinness Tour (depart Navan base by 9:15 AM).',
    items: [
      { time: '8:00 AM – 9:15 AM', startHour: 8.0, endHour: 9.25, dur: '1.25h', activity: '☕ Breakfast at Navan Base', type: 'dining', tag: 'BREAKFAST', desc: 'Coffee, tea, and breakfast at the Navan house before heading to Dublin.' },
      { time: '9:15 AM – 10:15 AM', startHour: 9.25, endHour: 10.25, dur: '1h', activity: '🚗 Drive Navan → Dublin (Guinness)', type: 'drive', tag: 'DRIVE', desc: '45 km / 28 mi morning drive down M3 into Dublin Liberties.' },
      { time: '10:30 AM – 12:30 PM', startHour: 10.5, endHour: 12.5, dur: '2h', activity: '🍺 Guinness Storehouse Bar Tour (10:30 AM)', type: 'sight', reserved: true, anchor: true, tag: 'CONFIRMED BOOKING', note: '10:30 AM entry', desc: 'Confirmed booking. Exclusive VIP bar tour, Guinness Academy & pint at 360° Gravity Bar.' },
      { time: '12:30 PM – 2:00 PM', startHour: 12.5, endHour: 14.0, dur: '1.5h', activity: '🍽️ Lunch in Liberties / The Brazen Head', type: 'dining', tag: 'LUNCH', desc: 'Hearty lunch in the historic Liberties / Dublin’s oldest pub.' },
      { time: '2:00 PM – 3:00 PM', startHour: 14.0, endHour: 15.0, dur: '1h', activity: '🚗 Drive Dublin → Boyne Valley', type: 'drive', tag: 'DRIVE', desc: 'Drive north to Newgrange World Heritage site.' },
      { time: '3:00 PM – 5:00 PM', startHour: 15.0, endHour: 17.0, dur: '2h', activity: '🪨 Newgrange UNESCO Passage Tomb', type: 'sight', tag: 'PLANNED VISIT', desc: '5,200-year-old Stone Age monument (older than Stonehenge & Pyramids).' },
      { time: '5:00 PM – 6:00 PM', startHour: 17.0, endHour: 18.0, dur: '1h', activity: '🚗 Drive to Dublin City Centre', type: 'drive', tag: 'DRIVE', desc: 'Head back into central Dublin for dinner & pub evening.' },
      { time: '6:00 PM – 7:30 PM', startHour: 18.0, endHour: 19.5, dur: '1.5h', activity: '🍽️ The Old Storehouse Tavern Dinner', type: 'dining', reserved: true, tag: 'TENTATIVE RESERVATION', desc: 'Classic Dublin tavern dinner before the music crawl in Temple Bar.' },
      { time: '7:30 PM – 11:00 PM', startHour: 19.5, endHour: 23.0, dur: '3.5h', activity: '🍻 DUBLIN PUB CRAWL (Temple Bar → Bad Bobs)', type: 'sight', tag: 'PUB CRAWL', desc: 'Live music crawl through iconic historic pubs.' },
      { time: '11:00 PM – 11:45 PM', startHour: 23.0, endHour: 23.75, dur: '45m', activity: '🚗 Return Drive to Navan Base', type: 'drive', tag: 'DRIVE', desc: 'Night highway drive back to Navan house.' },
    ],
  },
  {
    dayNumber: 12,
    date: 'Oct 13 (Tue)',
    region: 'dublin',
    color: '#f59e0b',
    title: "MOM'S BIRTHDAY CELEBRATION! 🎂",
    base: 'Navan Home (Dublin area)',
    route: 'Navan → Dublin (Brunch & Shopping) → Navan (Dress Up) → Dublin (Mister S)',
    isTransfer: false,
    driveHours: 1.5,
    special: true,
    weather: '🎂 15°C / 59°F · Mild & celebration ready',
    outfit: '👗 FANCY FORMAL / COCKTAIL for Mister S dinner; casual chic for daytime',
    budget: { driving: 1.5, sightseeing: 3.5, dining: 4.0, free: 2.0 },
    note: "🎂 Mom's Birthday! 👗 Fancy outfit for Mister S (24hr cancellation window).",
    items: [
      { time: '9:00 AM – 10:00 AM', startHour: 9.0, endHour: 10.0, dur: '1h', activity: '☕ Sleep In (Bar Crawl Recovery)', type: 'free', tag: 'REST', desc: 'Well-deserved late morning wakeup.' },
      { time: '10:00 AM – 11:30 AM', startHour: 10.0, endHour: 11.5, dur: '1.5h', activity: '🍳 Mom’s Birthday Brunch: Bread 41 / Elliots', type: 'dining', anchor: true, tag: 'BDAY BRUNCH', desc: 'Famous Dublin pastries, sourdough, and brunch treats for Mom.' },
      { time: '11:30 AM – 12:30 PM', startHour: 11.5, endHour: 12.5, dur: '1h', activity: '🚗 Drive into Central Dublin', type: 'drive', tag: 'DRIVE', desc: 'Drive in for birthday shopping and sightseeing.' },
      { time: '12:30 PM – 3:00 PM', startHour: 12.5, endHour: 15.0, dur: '2.5h', activity: '🏙️ Grafton St Shopping & Trinity College', type: 'sight', tag: 'CITY EXPLORE', desc: 'Grafton Street shops, Stephen’s Green, and Trinity campus walk.' },
      { time: '3:00 PM – 4:00 PM', startHour: 15.0, endHour: 16.0, dur: '1h', activity: "🍦 Murphy's Ice Cream + Loose Cannon Wine", type: 'dining', tag: 'TREATS', desc: 'Dingle sea salt ice cream and artisan wine bar toast.' },
      { time: '4:00 PM – 5:00 PM', startHour: 16.0, endHour: 17.0, dur: '1h', activity: '🚗 Drive back to Navan to Get Ready', type: 'drive', tag: 'DRIVE', desc: 'Head back to Navan to shower and change.' },
      { time: '5:00 PM – 6:15 PM', startHour: 17.0, endHour: 18.25, dur: '1.25h', activity: '👗 Get Ready in FANCY Birthday Outfits!', type: 'free', anchor: true, tag: 'DRESS UP', desc: 'Formal/fancy attire for Mom’s premier birthday dinner!' },
      { time: '6:15 PM – 7:00 PM', startHour: 18.25, endHour: 19.0, dur: '45m', activity: '🚗 Drive Navan → Mister S (Camden St, Dublin)', type: 'drive', tag: 'DRIVE', desc: 'Drive in to Camden Street dining quarter.' },
      { time: '7:00 PM – 9:30 PM', startHour: 19.0, endHour: 21.5, dur: '2.5h', activity: '🎂🍽️ MISTER S BIRTHDAY DINNER', type: 'dining', reserved: true, anchor: true, tag: 'CONFIRMED RESERVATION', note: '24hr cancellation cutoff', desc: 'Confirmed table for 7:00 PM. High-end wood-fired cuisine, steaks, and birthday celebration!' },
      { time: '9:30 PM – 11:30 PM', startHour: 21.5, endHour: 23.5, dur: '2h', activity: '🍻 Birthday Celebration Drinks in Dublin', type: 'dining', tag: 'CELEBRATE', desc: 'Cocktails and pints toast to Mom!' },
    ],
  },
  {
    dayNumber: 13,
    date: 'Oct 14 (Wed)',
    region: 'dublin',
    color: '#f59e0b',
    title: 'Departure & Flight Home 🛫',
    base: 'Navan Home (Check-out)',
    route: 'Navan → Dublin Airport (DUB)',
    isTransfer: true,
    driveHours: 1.0,
    special: false,
    weather: '🛫 13°C / 55°F · Crisp autumn breeze',
    outfit: '👟 Airport & flight travel layers',
    budget: { driving: 1.0, sightseeing: 0.0, dining: 1.5, free: 2.0 },
    items: [
      { time: '8:00 AM – 9:30 AM', startHour: 8.0, endHour: 9.5, dur: '1.5h', activity: '☕ Final Irish Breakfast & Packing', type: 'free', tag: 'PACKING', desc: 'Pack all souvenirs and check out of Navan Home.' },
      { time: '9:30 AM – 10:00 AM', startHour: 9.5, endHour: 10.0, dur: '30m', activity: '🏡 Check out Navan Home', type: 'housing', tag: 'CHECK-OUT', note: 'Check out by 11:00 AM', desc: 'Final house checkout and car loading.' },
      { time: '10:00 AM – 10:50 AM', startHour: 10.0, endHour: 10.83, dur: '50m', activity: '🚗 Drive Navan → Dublin Airport (DUB)', type: 'drive', tag: 'AIRPORT DRIVE', desc: 'Direct drive down M3/M50 to Dublin Airport Terminal.' },
      { time: '11:00 AM – 12:30 PM', startHour: 11.0, endHour: 12.5, dur: '1.5h', activity: '🚗 Return Rental Car & Check-in', type: 'housing', tag: 'CAR RETURN', desc: 'Gas up car, return keys to rental depot, bag drop.' },
      { time: '1:00 PM+', startHour: 13.0, endHour: 16.0, dur: '3h', activity: '🛫 Departure Flight Home', type: 'sight', anchor: true, tag: 'FLIGHT HOME', desc: 'Board flight home with memories of an incredible Ireland adventure!' },
    ],
  }
];

// ── Restaurants by city ───────────────────────────────────────
const restaurants = [
  { name: 'Holohans Pantry', city: 'Belfast', cuisine: 'Fine Dining / Boxty', booked: true, bookingTime: 'Oct 2 @ 7:00 PM', cancelPolicy: '48hr cancellation', notes: 'Traditional Irish boxty & seafood on University Rd. Confirmed reservation.' },
  { name: 'Common Market', city: 'Belfast', cuisine: 'Street Food Hall', booked: false, notes: 'Great casual lunch spot with diverse food vendors.' },
  { name: 'Duke of York', city: 'Belfast', cuisine: 'Historic Pub', booked: false, notes: 'Famous cobblestone beer garden in the Cathedral Quarter.' },
  { name: 'Bittles Bar', city: 'Belfast', cuisine: 'Flatiron Pub', booked: false, notes: 'Quirky triangular pub with great whiskeys and draft Guinness.' },
  { name: 'Mourne Seafood', city: 'Dundrum', cuisine: 'Seafood', booked: true, bookingTime: 'Oct 3 @ 7:15 PM (Tentative)', cancelPolicy: 'Table held', notes: 'Fresh local coastal shellfish 35m from Newry base.' },
  { name: 'Donnellys of Barna', city: 'Galway', cuisine: 'Seafood Pub', booked: false, notes: 'Pub by the beach in Barna village, fresh Atlantic oysters.' },
  { name: 'Kirwans', city: 'Galway', cuisine: 'Seafood Bar', booked: true, bookingTime: 'Oct 6 @ 7:00 PM', cancelPolicy: 'Confirmed', notes: 'In the heart of Latin Quarter. Exceptional local fish dishes.' },
  { name: 'Dough Bros', city: 'Galway', cuisine: 'Neapolitan Pizza', booked: false, notes: 'Ranked top pizza in Ireland. Great casual option.' },
  { name: 'Ruibin', city: 'Galway', cuisine: 'Modern Irish', booked: false, notes: 'Stunning dockside restaurant with local seasonal produce.' },
  { name: 'Out of the Blue', city: 'Dingle', cuisine: 'Seafood Only', booked: false, notes: 'No chips, no meat, only whatever was caught that morning!' },
  { name: 'Fishbox', city: 'Dingle', cuisine: 'Fish & Chips', booked: false, notes: 'Family-owned trawler-to-table casual seafood.' },
  { name: 'Dick Macks', city: 'Dingle', cuisine: 'Classic Pub', booked: false, notes: 'Historic pub + leather craftsman workshop.' },
  { name: 'Cronins', city: 'Killarney', cuisine: 'Trad Gastropub', booked: true, bookingTime: 'Oct 8 @ 7:30 PM', cancelPolicy: 'Confirmed', notes: 'Beloved dining institution in Killarney.' },
  { name: 'Mad Monk', city: 'Killarney', cuisine: 'Seafood & Steaks', booked: true, bookingTime: 'Oct 9 @ 6:00 PM', cancelPolicy: '48hr cancellation', notes: 'High-end dining. Strict 48h cancellation policy.' },
  { name: 'Mister S', city: 'Dublin', cuisine: 'Wood-fired Fine Dining', booked: true, bookingTime: 'Oct 13 @ 7:00 PM', cancelPolicy: '24hr cancellation', notes: "Mom's Birthday dinner! Camden St. Dress fancy." },
  { name: 'Old Storehouse', city: 'Dublin', cuisine: 'Traditional Pub', booked: true, bookingTime: 'Oct 12 @ 5:30 PM (Tentative)', cancelPolicy: 'Held', notes: 'Hearty dinner in Temple Bar before the pub crawl.' },
  { name: 'Bread 41', city: 'Dublin', cuisine: 'Artisan Bakery', booked: false, notes: 'Legendary pastries, morning buns, and brunch.' },
  { name: 'Brazen Head', city: 'Dublin', cuisine: 'Historic Pub', booked: false, notes: 'Oldest pub in Ireland (est. 1198) on Bridge Street.' }
];

// ── Confirmed & Tracked Reservations ───────────────────────────
const reservations = [
  { date: 'Oct 2', time: '7:00 PM', name: 'Holohans Pantry', location: 'Belfast', type: 'dining', status: 'Confirmed', cancelPolicy: '48hr cancellation', notes: 'First night dinner in Belfast. Traditional Irish boxty.' },
  { date: 'Oct 3', time: '7:15 PM', name: 'Mourne Seafood', location: 'Dundrum', type: 'dining', status: 'Tentative', cancelPolicy: 'Call if modifying', notes: 'Fresh local coastal seafood.' },
  { date: 'Oct 6', time: '7:00 PM', name: 'Kirwans Seafood Bar', location: 'Galway', type: 'dining', status: 'Confirmed', cancelPolicy: 'Standard', notes: 'Latin Quarter fine seafood.' },
  { date: 'Oct 8', time: '7:30 PM', name: 'Cronins Restaurant', location: 'Killarney', type: 'dining', status: 'Confirmed', cancelPolicy: 'Standard', notes: 'Killarney town centre.' },
  { date: 'Oct 9', time: '6:00 PM', name: 'Mad Monk', location: 'Killarney', type: 'dining', status: 'Confirmed', cancelPolicy: '48hr cancellation', notes: 'Strict 48hr cancellation cutoff. High-end dining.' },
  { date: 'Oct 12', time: '10:30 AM', name: 'Guinness Storehouse Bar Tour', location: 'Dublin', type: 'activity', status: 'Confirmed', cancelPolicy: 'Non-refundable', notes: 'Leave Navan by 9:15 AM. 10:30 AM reserved VIP bar tour & Gravity Bar.' },
  { date: 'Oct 12', time: '6:00 PM', name: 'Old Storehouse', location: 'Dublin', type: 'dining', status: 'Tentative', cancelPolicy: 'Standard', notes: 'Pre-crawl dinner in Temple Bar.' },
  { date: 'Oct 13', time: '7:00 PM', name: 'Mister S (Mom’s Bday Dinner)', location: 'Dublin', type: 'dining', status: 'Confirmed', cancelPolicy: '24hr cancellation', special: true, notes: "Mom's Birthday Premier Celebration! Fancy outfits required." },
  { date: 'Oct 2–5', time: 'Check-in 11:30 AM', name: 'Walnut Retreat', location: 'Newry', type: 'lodging', status: 'Confirmed', cancelPolicy: 'Booked', notes: 'Base #1 (3 nights). Check-out Oct 5 by 11:00 AM.' },
  { date: 'Oct 5–8', time: 'Check-in 4:00 PM', name: 'Spiddal Villa', location: 'Spiddal (Galway)', type: 'lodging', status: 'Confirmed', cancelPolicy: 'Booked', notes: 'Base #2 (3 nights). Check-out Oct 8 by 11:00 AM.' },
  { date: 'Oct 8–11', time: 'Check-in 12:00 PM', name: 'Milltown House', location: 'Killarney', type: 'lodging', status: 'Confirmed', cancelPolicy: 'Booked', notes: 'Base #3 (3 nights). Check-out Oct 11 by 8:00 AM.' },
  { date: 'Oct 11–14', time: 'Check-in 3:00 PM', name: 'Navan Home', location: 'Navan (Dublin)', type: 'lodging', status: 'Confirmed', cancelPolicy: 'Booked', notes: 'Base #4 (3 nights). Check-out Oct 14 by 11:00 AM.' }
];

// ── Distances Matrix ──────────────────────────────────────────
const distances = [
  { from: 'Dublin Airport', to: 'Newry (Walnut Retreat)', time: '1h 10m', urgency: 'low', transfer: true, notes: 'M1/A1 highway corridor to Base #1.' },
  { from: 'Newry Base', to: 'Belfast Titanic Quarter', time: '50m', urgency: 'low', transfer: false, notes: 'Straight up A1.' },
  { from: 'Newry Base', to: "Giant's Causeway", time: '2h 15m', urgency: 'high', transfer: false, notes: 'Antrim coast day trip.' },
  { from: 'Newry Base', to: 'Mourne Seafood (Dundrum)', time: '40m', urgency: 'low', transfer: false, notes: 'Coastal drive.' },
  { from: 'Newry Base (Walnut Retreat)', to: 'Spiddal Villa (Galway)', time: '3h 45m', urgency: 'high', transfer: true, notes: 'MAJOR BASE MOVE #1 (Cross-country M1/M6).' },
  { from: 'Spiddal Villa', to: 'Cliffs of Moher', time: '1h 15m', urgency: 'med', transfer: false, notes: 'Around Galway Bay into Clare.' },
  { from: 'Spiddal Villa', to: 'Kylemore Abbey & Connemara NP', time: '1h 15m', urgency: 'med', transfer: false, notes: 'Wild bog & mountain road.' },
  { from: 'Spiddal Villa', to: 'Galway Latin Quarter', time: '25m', urgency: 'low', transfer: false, notes: 'Local coastal road.' },
  { from: 'Spiddal Villa (Galway)', to: 'Milltown House (Killarney)', time: '3h 00m', urgency: 'high', transfer: true, notes: 'MAJOR BASE MOVE #2 (South via Limerick).' },
  { from: 'Milltown Base', to: 'Dingle Peninsula / Slea Head', time: '1h 15m', urgency: 'med', transfer: false, notes: 'Scenic Atlantic coast.' },
  { from: 'Milltown Base', to: 'Gap of Dunloe', time: '20m', urgency: 'low', transfer: false, notes: 'Short jump.' },
  { from: 'Milltown Base (Killarney)', to: 'Rock of Cashel', time: '1h 50m', urgency: 'med', transfer: true, notes: 'Eastbound en route to Navan.' },
  { from: 'Rock of Cashel', to: 'Kilkenny Castle', time: '55m', urgency: 'low', transfer: true, notes: 'Midway pitstop.' },
  { from: 'Kilkenny', to: 'Navan Home (Dublin Base)', time: '1h 45m', urgency: 'med', transfer: true, notes: 'MAJOR BASE MOVE #3 (Final housing check-in).' },
  { from: 'Navan Home', to: 'Guinness Storehouse (Dublin)', time: '50m', urgency: 'low', transfer: false, notes: 'M3 motorway into city.' },
  { from: 'Navan Home', to: 'Newgrange Monument', time: '20m', urgency: 'low', transfer: false, notes: 'Boyne Valley local drive.' },
  { from: 'Navan Home', to: 'Dublin Airport (DUB)', time: '45m', urgency: 'low', transfer: true, notes: 'Final departure drive home.' }
];
